name: quantumflo_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - streamlit=1.28.2
  - pandas=2.1.3
  - numpy=1.26.2
  - scikit-learn=1.3.2
  - xgboost=2.0.2
  - scipy=1.11.4
  - prophet=1.1.5